Sascha Spors,
Professorship Signal Theory and Digital Signal Processing,
Institute of Communications Engineering (INT),
Faculty of Computer Science and Electrical Engineering (IEF),
University of Rostock,
Germany

# Tutorial Digital Signal Processing

**Solving a Set of Linear Equations Using Matrices**,

- lecture: https://github.com/spatialaudio/digital-signal-processing-lecture
- tutorial: https://github.com/spatialaudio/digital-signal-processing-exercises

Feel free to contact lecturer frank.schultz@uni-rostock.de

# Solving a Set of Linear Equations Using Matrices 

For example a set of linear equations:
$$
\begin{matrix}
2x_1 &+& 1x_2 & -&1x_3 &= &8\\
-3x_1 &-&1x_2 &+& 2x_3 &= &-11\\
-2x_1 &+& 1x_2&+ & 2x_3 &= &-3
\end{matrix}
$$
can be transformed to matrix and vector notation:
$$
\textbf{A}=\begin{bmatrix}
2 & 1 & -1\\
-3 & -1 & 2\\
-2 &1 & 2
\end{bmatrix} 
\quad;\quad 
\textbf{x}=\begin{bmatrix}
x_1 \\
x_2 \\
x_3 
\end{bmatrix} 
\quad;\quad 
\textbf{b}=\begin{bmatrix}
8 \\
-11 \\
-3 
\end{bmatrix} 
$$
or in a more simple way as:

$$
\textbf{A} \textbf{x}=\textbf{b}
$$

To solve this problem we need to invert $\textbf{A}$:

$$
\textbf{x}=\textbf{A}^{-1}\textbf{b}
$$

In [1]:
import numpy as np
# Programm it

A = [[2,1,-1],[-3,-1,2],[-2,1,2]]
A = np.matrix(A)

b = [8,-11,-3]
b = np.array(b)

print("b=",b,"\n")
print("A=",A)

b= [  8 -11  -3] 

A= [[ 2  1 -1]
 [-3 -1  2]
 [-2  1  2]]


In [2]:
x = np.dot(A**-1,b)
print(x)

[[ 2.  3. -1.]]


Is it right? I think so!